# Generated by Django 6.0.3 on 2026-07-15 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short name of the feature (e.g. Lead Management)', max_length=255)),
                ('code', models.SlugField(help_text='Code identifier for permission checks (e.g. lead_management). Unique per product.')),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this feature offers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the CRM module/service (e.g. Sales CRM)', max_length=255)),
                ('slug', models.SlugField(help_text='Unique slug for URL routing', unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the CRM module')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this product is active and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Designates whether this feature is active in the plan')),
                ('limit_value', models.CharField(blank=True, help_text="Custom feature limit value if any (e.g. '500 leads', '5 users')", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='crm.feature')),
            ],
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the pricing plan (e.g. Starter, Professional)', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Cost of the plan', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Three-letter currency code', max_length=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one_time', 'One-time')], default='monthly', help_text='Frequency of billing', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this plan is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('features', models.ManyToManyField(help_text='Features included in this pricing plan', related_name='plans', through='crm.PlanFeature', to='crm.feature')),
                ('product', models.ForeignKey(help_text='The CRM product/module this plan belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='crm.product')),
            ],
        ),
        migrations.AddField(
            model_name='planfeature',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='crm.pricingplan'),
        ),
        migrations.AddField(
            model_name='feature',
            name='product',
            field=models.ForeignKey(help_text='The CRM product/module this feature belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='crm.product'),
        ),
        migrations.AlterUniqueTogether(
            name='planfeature',
            unique_together={('plan', 'feature')},
        ),
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together={('product', 'code')},
        ),
    ]
