# Generated by Django 6.0.3 on 2026-07-15 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short name of the module (e.g. Lead Management)', max_length=255)),
                ('code', models.SlugField(help_text='Code identifier for permission checks. Unique per product.')),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this module offers')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this module is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which this module is displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the SaaS module/service (e.g. Sales CRM)', max_length=255)),
                ('slug', models.SlugField(help_text='Unique slug for URL routing', unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the product')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this product is active and visible')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which this product is displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Designates whether this module is active in the plan')),
                ('limit_value', models.CharField(blank=True, help_text="Custom module limit value if any (e.g. '500 leads', '5 users')", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_modules', to='catalog.module')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the pricing plan (e.g. Starter, Professional)', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Cost of the plan', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Three-letter currency code', max_length=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one_time', 'One-time')], default='monthly', help_text='Frequency of billing', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this plan is active')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which this plan is displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modules', models.ManyToManyField(help_text='Modules included in this pricing plan', related_name='plans', through='catalog.PlanModule', to='catalog.module')),
                ('product', models.ForeignKey(help_text='The product this plan belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='catalog.product')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.AddField(
            model_name='planmodule',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_modules', to='catalog.pricingplan'),
        ),
        migrations.AddField(
            model_name='module',
            name='product',
            field=models.ForeignKey(help_text='The product this module belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='catalog.product'),
        ),
        migrations.AlterUniqueTogether(
            name='planmodule',
            unique_together={('plan', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('product', 'code')},
        ),
    ]
