# Generated by Django 6.0.7 on 2026-07-16 17:19

import catalog.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[catalog.models.product.validate_product_image]),
        ),
    ]
