# Generated by Django 6.0.7 on 2026-07-17 13:30

import catalog.models.product
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the professional service (e.g. CRM Consultation)', max_length=255)),
                ('slug', models.SlugField(help_text='Unique slug for URL routing', unique=True)),
                ('short_description', models.CharField(help_text='Brief summary of the service', max_length=500)),
                ('full_description', models.TextField(blank=True, help_text='Detailed description of the service')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', validators=[catalog.models.product.validate_product_image])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this service is active and visible')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which this service is displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short name/description of the feature (e.g. Email Support)', max_length=255)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which this feature is displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(help_text='The service this feature belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='catalog.service')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
