# Generated by Django 6.0.7 on 2026-07-17 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_service_servicefeature'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricingplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='service',
            field=models.ForeignKey(blank=True, help_text='The service this plan belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='catalog.service'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='product',
            field=models.ForeignKey(blank=True, help_text='The product this plan belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='catalog.product'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the discount (e.g. Winter Sale)', max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', help_text='Type of discount (Percentage or Fixed Amount)', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount value (percentage e.g. 20.00 or amount e.g. 50.00)', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Manually enable/disable the discount')),
                ('start_date', models.DateTimeField(blank=True, help_text='Start date/time of the discount (optional)', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='End date/time of the discount (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pricing_plan', models.ForeignKey(help_text='The pricing plan this discount applies to', on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='catalog.pricingplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
